services:
    marttiphpbb.allusersgroupstempvars.listener:
        class: marttiphpbb\allusersgroupstempvars\event\listener
        arguments:
            - '@dbal.conn'
            - '%tables.user_group%'
        tags:
            - { name: event.listener }
